# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gE3AkOvomItbvXq25I04AarvW6Bj09bg
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# ── Page Config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="E-Commerce Dashboard",
    page_icon="🛒",
    layout="wide"
)

# ── Load Data ─────────────────────────────────────────────────────────────────
@st.cache_data
def load_data():
    main    = pd.read_csv('Dashboard/main_data.csv',
                          parse_dates=['order_purchase_timestamp'])
    payment = pd.read_csv('Dashboard/payment_data.csv',
                          parse_dates=['order_purchase_timestamp'])
    rfm     = pd.read_csv('Dashboard/rfm_data.csv')
    return main, payment, rfm

main_df, pay_df, rfm_df = load_data()

# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.title("🛒 E-Commerce")
    st.markdown("**Brazilian E-Commerce Public Dataset**")
    st.markdown("---")

    st.subheader("📅 Filter Periode")
    min_date = main_df['order_purchase_timestamp'].min().date()
    max_date = main_df['order_purchase_timestamp'].max().date()

    start_date = st.date_input("Dari", value=min_date,
                               min_value=min_date, max_value=max_date)
    end_date   = st.date_input("Sampai", value=max_date,
                               min_value=min_date, max_value=max_date)
    st.markdown("---")
    top_n = st.slider("Jumlah Top Kategori/State", 5, 15, 10)

# ── Filter ────────────────────────────────────────────────────────────────────
mask = (
    (main_df['order_purchase_timestamp'].dt.date >= start_date) &
    (main_df['order_purchase_timestamp'].dt.date <= end_date)
)
df = main_df[mask].copy()

pay_mask = (
    (pay_df['order_purchase_timestamp'].dt.date >= start_date) &
    (pay_df['order_purchase_timestamp'].dt.date <= end_date)
)
pay = pay_df[pay_mask].copy()

# ── Header ────────────────────────────────────────────────────────────────────
st.title("🛒 Brazilian E-Commerce Analytics Dashboard")
st.caption(f"Periode: {start_date} s/d {end_date}")
st.markdown("---")

# ── Metrics ───────────────────────────────────────────────────────────────────
rev_total = (
    df[['order_id']].drop_duplicates()
    .merge(pay_df[['order_id','total_payment']].drop_duplicates('order_id'),
           on='order_id', how='left')['total_payment'].sum()
)

col1, col2, col3, col4 = st.columns(4)
col1.metric("📦 Total Orders",  f"{df['order_id'].nunique():,}")
col2.metric("💰 Total Revenue", f"R$ {rev_total/1e6:.2f}M")
col3.metric("⭐ Avg Review",     f"{df['review_score'].mean():.2f} / 5")
col4.metric("🚚 Late Delivery",  f"{(df['delivery_delay_days']>0).mean()*100:.1f}%")
st.markdown("---")

# ── Tabs ──────────────────────────────────────────────────────────────────────
tab1, tab2, tab3, tab4 = st.tabs([
    "📦 Delivery & Review",
    "💳 Revenue & Payment",
    "👥 RFM Segmentation",
    "🗺️  Geospatial"
])

# ══════════════════════════════════════════════════════════════════════════════
# TAB 1 — DELIVERY & REVIEW
# ══════════════════════════════════════════════════════════════════════════════
with tab1:
    st.subheader("Pertanyaan 1: Kategori dengan Delivery Delay & Review Score Terendah")
    st.caption("Jan 2017 – Agt 2018 | min. 100 orders per kategori")

    cat_df = df.groupby('product_category_name_english').agg(
        avg_delay    = ('delivery_delay_days', 'mean'),
        avg_review   = ('review_score', 'mean'),
        total_orders = ('order_id', 'nunique')
    ).reset_index()
    cat_df = cat_df[cat_df['total_orders'] >= 100].copy()
    cat_df['label'] = cat_df['product_category_name_english'].str.replace('_',' ').str.title()

    col_a, col_b = st.columns(2)

    # Chart 1: Delivery Delay
    with col_a:
        st.markdown("##### 🔵 Delivery Delay Terlama")
        top_d = cat_df.nlargest(top_n, 'avg_delay').sort_values('avg_delay')
        fig, ax = plt.subplots(figsize=(7, top_n * 0.5))
        bars = ax.barh(top_d['label'], top_d['avg_delay'],
                       color='#1976D2', edgecolor='white')
        ax.axvline(0, color='black', lw=0.8, linestyle='--')
        ax.set_xlabel('Avg Delivery Delay (days)\n(negatif = lebih cepat dari estimasi)')
        ax.set_title(f'Top {top_n} Kategori — Delivery Delay', fontweight='bold')
        for bar, v in zip(bars, top_d['avg_delay']):
            ax.text(bar.get_width() - 0.3,
                    bar.get_y() + bar.get_height()/2,
                    f'{v:.1f}d', va='center', ha='right',
                    fontsize=8, color='white', fontweight='bold')
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

    # Chart 2: Review Score
    with col_b:
        st.markdown("##### Review Score Kategori Delay Tertinggi")
        top_d_rev = cat_df.nlargest(top_n, 'avg_delay').sort_values('avg_review')
        overall   = cat_df['avg_review'].mean()
        fig, ax   = plt.subplots(figsize=(7, top_n * 0.5))
        bars = ax.barh(top_d_rev['label'], top_d_rev['avg_review'],
                       color='#1976D2', edgecolor='white')
        ax.axvline(4.0, color='#d62728', lw=1.5, linestyle='--',
                   label='Batas kepuasan: 4.0')
        ax.axvline(overall, color='navy', lw=1.2, linestyle=':',
                   label=f'Overall avg: {overall:.2f}')
        ax.set_xlabel('Avg Review Score (1–5)')
        ax.set_xlim(3.5, 5.0)
        ax.legend(fontsize=9)
        ax.set_title(f'Review Score — Top {top_n} Delay', fontweight='bold')
        for bar, v in zip(bars, top_d_rev['avg_review']):
            ax.text(bar.get_width() + 0.01,
                    bar.get_y() + bar.get_height()/2,
                    f'{v:.2f}', va='center', fontsize=8)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

    # Chart 3: Scatter korelasi
    st.markdown("##### 📊 Korelasi Delivery Delay vs Review Score")
    col_c, col_d = st.columns([2, 1])

    with col_c:
        corr = cat_df['avg_delay'].corr(cat_df['avg_review'])
        fig, ax = plt.subplots(figsize=(8, 5))
        sc = ax.scatter(
            cat_df['avg_delay'], cat_df['avg_review'],
            s=cat_df['total_orders']/8, alpha=0.6,
            c=cat_df['avg_review'], cmap='RdYlGn',
            edgecolors='grey', linewidth=0.4
        )
        z   = np.polyfit(cat_df['avg_delay'], cat_df['avg_review'], 1)
        x_l = np.linspace(cat_df['avg_delay'].min(), cat_df['avg_delay'].max(), 100)
        ax.plot(x_l, np.poly1d(z)(x_l), 'navy', lw=1.5, linestyle='--',
                label=f'Trendline (r={corr:.3f})')
        plt.colorbar(sc, ax=ax, label='Avg Review Score')
        ax.set_xlabel('Avg Delivery Delay (days)')
        ax.set_ylabel('Avg Review Score')
        ax.set_title('Korelasi Delay vs Review per Kategori\n(bubble = volume order)',
                     fontweight='bold')
        ax.legend()
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

    with col_d:
        st.markdown("##### Review per Delay Group")
        df['delay_group'] = pd.cut(
            df['delivery_delay_days'],
            bins=[-np.inf, -14, 0, 7, np.inf],
            labels=['Early\n>14d', 'On-time', 'Late\n1-7d', 'Very Late\n>7d']
        )
        dg = df.groupby('delay_group')['review_score'].mean().reset_index()
        fig, ax = plt.subplots(figsize=(5, 4))
        
        ax.bar(dg['delay_group'], dg['review_score'], color='#1976D2', edgecolor='white')
        ax.set_ylim(0, 5.5)
        ax.set_ylabel('Avg Review Score')
        ax.set_title('Review per\nDelay Group', fontweight='bold')
        for i, v in enumerate(dg['review_score']):
            ax.text(i, v + 0.07, f'{v:.2f}', ha='center', fontsize=9, fontweight='bold')
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

    # insight
    corr_order = df['delivery_delay_days'].corr(df['review_score'])
    late_n     = (df['delivery_delay_days'] > 0).sum()
    st.info(f"""
    📌 **Insight:** Korelasi order-level delay vs review = **{corr_order:.3f}** (negatif).
    {late_n:,} orders ({late_n/len(df)*100:.1f}%) terlambat pada periode ini.
    """)

# ══════════════════════════════════════════════════════════════════════════════
# TAB 2 — REVENUE & PAYMENT
# ══════════════════════════════════════════════════════════════════════════════
with tab2:
    st.subheader("Pertanyaan 2: Tren Revenue Bulanan & Distribusi Metode Pembayaran")

    monthly = pay.groupby('year_month').agg(
        total_revenue = ('total_payment', 'sum'),
        total_orders  = ('order_id', 'nunique')
    ).reset_index().sort_values('year_month')

    pay_type = pay.groupby('payment_type').agg(
        total_revenue = ('payment_value', 'sum'),
        total_txn     = ('order_id', 'nunique'),
        avg_value     = ('payment_value', 'mean'),
        avg_install   = ('payment_installments', 'mean')
    ).reset_index().sort_values('total_revenue', ascending=False)

    col_e, col_f = st.columns([3, 2])

    with col_e:
        st.markdown("##### 📈 Monthly Revenue Trend")
        fig, ax = plt.subplots(figsize=(9, 4.5))
        x = range(len(monthly))
        ax.fill_between(x, monthly['total_revenue'], alpha=0.15, color='#1976D2')
        ax.plot(x, monthly['total_revenue'], marker='o', color='#1976D2',
                lw=2.2, markersize=5)
        if len(monthly) > 0:
            pi = monthly['total_revenue'].idxmax()
            ax.annotate(
                f"Peak\nR${monthly.loc[pi,'total_revenue']:,.0f}",
                xy=(pi, monthly.loc[pi,'total_revenue']),
                xytext=(max(0, pi-3), monthly.loc[pi,'total_revenue']*0.88),
                arrowprops=dict(arrowstyle='->', color='darkred'),
                fontsize=8.5, color='darkred'
            )
        ax.set_xticks(x)
        ax.set_xticklabels(monthly['year_month'], rotation=45, ha='right', fontsize=7.5)
        ax.yaxis.set_major_formatter(
            mticker.FuncFormatter(lambda v, _: f'R${v/1e6:.1f}M')
        )
        ax.set_title('Monthly Revenue Trend', fontweight='bold')
        ax.set_ylabel('Revenue (R$)')
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

    # Pie chart
    with col_f:
        st.markdown("##### 💳 Revenue Share by Payment Type")
        fig, ax = plt.subplots(figsize=(5, 5))
        pay_colors = ['#1976D2','#43A047','#FB8C00','#8E24AA']
        labels     = pay_type['payment_type'].str.replace('_',' ').str.title()

        def smart_autopct(pct):
            return f'{pct:.1f}%' if pct > 5 else ''

        wedges, texts, autotexts = ax.pie(
            pay_type['total_revenue'],
            labels=None,
            autopct=smart_autopct,
            colors=pay_colors[:len(pay_type)],
            startangle=90,
            pctdistance=0.75,
            wedgeprops=dict(width=0.55)
        )
        for t in autotexts:
            t.set_fontsize(11)
            t.set_fontweight('bold')
            t.set_color('white')

        legend_labels = [
            f'{l} ({v:.1f}%)' for l, v in zip(
                labels,
                pay_type['total_revenue'] /
                pay_type['total_revenue'].sum() * 100
            )
        ]
        ax.legend(wedges, legend_labels,
                  title='Payment Method',
                  loc='lower center',
                  bbox_to_anchor=(0.5, -0.15),
                  ncol=2, fontsize=9, title_fontsize=9)
        ax.set_title('Revenue Share\nby Payment Method', fontweight='bold', pad=15)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

    # Avg value & installments
    st.markdown("##### 💰 Avg Nilai Transaksi & Cicilan per Metode")
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    lbls = pay_type['payment_type'].str.replace('_',' ').str.title()
    

    axes[0].bar(lbls, pay_type['avg_value'], color='#1976D2', edgecolor='white')
    axes[0].set_title('Avg Transaction Value', fontweight='bold')
    axes[0].set_ylabel('Avg Value (R$)')
    for i, v in enumerate(pay_type['avg_value']):
        axes[0].text(i, v + 1, f'R${v:.0f}', ha='center', fontsize=9)

    axes[1].bar(lbls, pay_type['avg_install'], color='#1976D2', edgecolor='white')
    axes[1].set_title('Avg Installments', fontweight='bold')
    axes[1].set_ylabel('Avg # Cicilan')
    for i, v in enumerate(pay_type['avg_install']):
        axes[1].text(i, v + 0.05, f'{v:.1f}x', ha='center', fontsize=9)

    plt.tight_layout()
    st.pyplot(fig)
    plt.close()

    # insight
    if len(monthly) > 1:
        best   = monthly.loc[monthly['total_revenue'].idxmax(), 'year_month']
        mom    = monthly['total_revenue'].pct_change().mean() * 100
        cc_pct = (
            pay_type[pay_type['payment_type']=='credit_card']['total_revenue'].sum()
            / pay_type['total_revenue'].sum() * 100
        )
        st.success(
            f"📌 **Insight:** Revenue puncak di **{best}**. "
            f"Rata-rata pertumbuhan MoM: **{mom:.1f}%**. "
            f"Credit card dominasi **{cc_pct:.1f}%** revenue — "
            f"preferensi cicilan khas pasar Brasil."
        )

# ══════════════════════════════════════════════════════════════════════════════
# TAB 3 — RFM SEGMENTATION
# ══════════════════════════════════════════════════════════════════════════════
with tab3:
    st.subheader("Analisis Lanjutan: RFM Customer Segmentation")
    st.markdown("Segmentasi pelanggan berdasarkan **Recency**, **Frequency**, dan **Monetary**.")

    seg = rfm_df.groupby('segment').agg(
        count          = ('customer_unique_id', 'count'),
        avg_recency    = ('recency', 'mean'),
        avg_frequency  = ('frequency', 'mean'),
        avg_monetary   = ('monetary', 'mean'),
        total_monetary = ('monetary', 'sum')
    ).reset_index().sort_values('count', ascending=False)

    # Metrics
    c1, c2, c3 = st.columns(3)
    champ  = seg[seg['segment']=='Champions']
    atrisk = seg[seg['segment']=='At Risk']
    potloy = seg[seg['segment']=='Potential Loyalists']

    if not champ.empty:
        c1.metric("🏆 Champions",
                  f"{int(champ['count'].values[0]):,}",
                  f"Avg R${champ['avg_monetary'].values[0]:,.0f}")
    if not atrisk.empty:
        c2.metric("⚠️ At Risk",
                  f"{int(atrisk['count'].values[0]):,}",
                  "Segmen terbesar — butuh win-back")
    if not potloy.empty:
        c3.metric("🌱 Potential Loyalists",
                  f"{int(potloy['count'].values[0]):,}",
                  f"Avg R${potloy['avg_monetary'].values[0]:,.0f}")

    col_g, col_h = st.columns(2)


    with col_g:
        st.markdown("##### 👥 Jumlah Pelanggan per Segmen")
        sc = seg.sort_values('count', ascending=True)
        fig, ax = plt.subplots(figsize=(7, 5))
        bars = ax.barh(sc['segment'], sc['count'],
                       color='#1976D2', edgecolor='white')
        for bar, v in zip(bars, sc['count']):
            ax.text(bar.get_width() + 100,
                    bar.get_y() + bar.get_height()/2,
                    f'{v:,}', va='center', fontsize=8.5)
        ax.set_xlim(0, sc['count'].max() * 1.25)
        ax.set_title('Customer Count per RFM Segment', fontweight='bold')
        ax.set_xlabel('Number of Customers')
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

    with col_h:
        st.markdown("##### 💰 Avg Spending per Segmen")
        sm = seg.sort_values('avg_monetary', ascending=True)
        fig, ax = plt.subplots(figsize=(7, 5))
        bars = ax.barh(sm['segment'], sm['avg_monetary'],
                       color='#43A047', edgecolor='white')
        for bar, v in zip(bars, sm['avg_monetary']):
            ax.text(bar.get_width() + 2,
                    bar.get_y() + bar.get_height()/2,
                    f'R${v:,.0f}', va='center', fontsize=8.5)
        ax.set_title('Avg Monetary per RFM Segment', fontweight='bold')
        ax.set_xlabel('Avg Monetary (BRL)')
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

    st.markdown("##### 📋 Tabel Ringkasan RFM")
    disp = seg.copy()
    disp['avg_recency']   = disp['avg_recency'].round(0).astype(int)
    disp['avg_frequency'] = disp['avg_frequency'].round(2)
    disp['avg_monetary']  = disp['avg_monetary'].map('R$ {:,.2f}'.format)
    disp['total_monetary']= disp['total_monetary'].map('R$ {:,.0f}'.format)
    disp.columns = ['Segment','Customers','Avg Recency (days)',
                    'Avg Frequency','Avg Monetary','Total Monetary']
    st.dataframe(disp, use_container_width=True)

    _at_risk = seg[seg['segment']=='At Risk']
    _champ   = seg[seg['segment']=='Champions']
    _pot     = seg[seg['segment']=='Potential Loyalists']
    _total   = seg['count'].sum()
 
    _ar_n   = int(_at_risk['count'].values[0])   if not _at_risk.empty else 0
    _ar_pct = _ar_n / _total * 100               if _total > 0 else 0
    _ch_n   = int(_champ['count'].values[0])     if not _champ.empty else 0
    _ch_mon = _champ['avg_monetary'].values[0]   if not _champ.empty else 0
    _pt_mon = _pot['avg_monetary'].values[0]     if not _pot.empty else 0

    # insight
    st.warning(
        f"📌 **Insight:** Segmen At Risk terbesar ({_ar_n:,} pelanggan / {_ar_pct:.1f}%) — "
        f"pernah aktif tapi mulai tidak kembali, butuh win-back campaign segera. "
        f"Champions ({_ch_n:,} pelanggan) avg monetary tertinggi R\\${_ch_mon:,.0f} — "
        f"pertahankan dengan program loyalty eksklusif. "
        f"Potential Loyalists avg R\\${_pt_mon:,.0f} — hampir setara Champions, "
        f"peluang upgrade terbesar."
    )

# ══════════════════════════════════════════════════════════════════════════════
# TAB 4 — GEOSPATIAL
# ══════════════════════════════════════════════════════════════════════════════
with tab4:
    st.subheader("Analisis Lanjutan: Distribusi Order & Revenue per State Brasil")

    state_df = (
        df[['order_id','customer_state','review_score','delivery_delay_days']]
        .drop_duplicates('order_id')
        .merge(
            pay_df[['order_id','total_payment']].drop_duplicates('order_id'),
            on='order_id', how='left'
        )
        .groupby('customer_state').agg(
            total_orders  = ('order_id', 'nunique'),
            total_revenue = ('total_payment', 'sum'),
            avg_review    = ('review_score', 'mean'),
            avg_delay     = ('delivery_delay_days', 'mean')
        ).reset_index()
        .sort_values('total_orders', ascending=False)
    )

    top15 = state_df.head(top_n)

    col_i, col_j = st.columns(2)

    # Orders & revenue
    with col_i:
        st.markdown("##### 📦 Orders by State")
        t1 = top15.sort_values('total_orders', ascending=True)
        fig, ax = plt.subplots(figsize=(7, top_n*0.5))
        ax.barh(t1['customer_state'], t1['total_orders'],
                color='#1976D2', edgecolor='white')
        ax.set_title(f'Top {top_n} States — Orders', fontweight='bold')
        for i, v in enumerate(t1['total_orders']):
            ax.text(v+100, i, f'{v:,}', va='center', fontsize=8)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

    with col_j:
        st.markdown("##### 💰 Revenue by State")
        t2 = top15.sort_values('total_revenue', ascending=True)
        fig, ax = plt.subplots(figsize=(7, top_n*0.5))
        ax.barh(t2['customer_state'], t2['total_revenue'],
                color='#43A047', edgecolor='white')
        ax.xaxis.set_major_formatter(
            mticker.FuncFormatter(lambda v, _: f'R${v/1e6:.1f}M')
        )
        ax.set_title(f'Top {top_n} States — Revenue', fontweight='bold')
        for i, v in enumerate(t2['total_revenue']):
            ax.text(v+1000, i, f'R${v/1e6:.1f}M', va='center', fontsize=8)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

    col_k, col_l = st.columns(2)

    # Review by state
    with col_k:
        st.markdown("##### ⭐ Avg Review by State")
        t3      = top15.sort_values('avg_review', ascending=True)
        overall_state = state_df['avg_review'].mean()
        fig, ax = plt.subplots(figsize=(7, top_n*0.5))
        ax.barh(t3['customer_state'], t3['avg_review'],
                color='#1976D2', edgecolor='white')
        ax.axvline(4.0, color='#d62728', lw=1.5, linestyle='--',
                   label='Batas kepuasan: 4.0')
        ax.axvline(overall_state, color='navy', lw=1.2, linestyle=':',
                   label=f'Overall avg: {overall_state:.2f}')
        ax.set_xlim(3.5, 5.0)
        ax.legend(fontsize=9)
        ax.set_title('Avg Review Score by State', fontweight='bold')
        for i, v in enumerate(t3['avg_review']):
            ax.text(v+0.01, i, f'{v:.2f}', va='center', fontsize=8)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

    # Delay by state
    with col_l:
        st.markdown("##### 🚚 Avg Delivery Delay by State")
        t4    = top15.sort_values('avg_delay', ascending=True)
        clrs4 = ['#d62728' if v > 0 else '#1976D2' for v in t4['avg_delay']]
        fig, ax = plt.subplots(figsize=(7, top_n*0.5))
        ax.barh(t4['customer_state'], t4['avg_delay'],
                color=clrs4, edgecolor='white')
        ax.axvline(0, color='black', lw=0.8, linestyle='--')
        ax.set_title('Avg Delivery Delay by State\n(negatif = lebih cepat)',
                     fontweight='bold')
        for i, v in enumerate(t4['avg_delay']):
            ax.text(v+0.05, i, f'{v:.1f}d', va='center', fontsize=8)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

    st.markdown("##### 📋 Tabel Lengkap per State")
    st.dataframe(
        state_df.style.format({
            'total_orders':  '{:,}',
            'total_revenue': 'R$ {:,.0f}',
            'avg_review':    '{:.2f}',
            'avg_delay':     '{:.1f}d'
        }),
        use_container_width=True
    )

    sp     = state_df[state_df['customer_state']=='SP']['total_orders'].values
    sp_pct = sp[0]/state_df['total_orders'].sum()*100 if len(sp)>0 else 0
    state_df['rev_per_order'] = state_df['total_revenue'] / state_df['total_orders']
    top2_rev = state_df.nlargest(2, 'rev_per_order')['customer_state'].tolist()
    
    # insight
    st.info(
        f"📌 **Insight:** Sao Paulo (SP) dominasi **{sp_pct:.1f}%** total orders. "
        f"State tier-2 review bagus tapi volume kecil — peluang ekspansi. "
        f"Revenue per order tertinggi di state **{top2_rev[0]}** dan **{top2_rev[1]}**."
    )

# ── Footer ────────────────────────────────────────────────────────────────────
st.markdown("---")
st.caption("📊 Brazilian E-Commerce Analytics | Proyek Akhir Dicoding | Dataset: Olist")